package StringOperations;


/**
* StringOperations/StringService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOperations.idl
* Wednesday, April 23, 2025 8:00:24 AM IST
*/

public interface StringService extends StringServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringService
